### ISSUE TITLE
Help to debug

### ISSUE THREAD

**Issue by tomp1k** [lipov3cz3k/esphome-bspool-chlorinator#1]
Hi,

First of all, thank you very much for your work!

I built the component as you described and installed the example.yaml configuration, unfortunately I can't read the data from the salinator. The logs show the following. I'd appreciate help in determining the cause.

Thank you very much in advance!

<img width="1272" alt="Image" src="https://github.com/user-attachments/assets/fe109098-650b-4a3b-83c5-c1c7f4d6b854" />

**Comment by lipov3cz3k** [comment]
Hi,
it seems that ESP do not get any response from chlorinator. I would recommend disabling all the sensors except few (during my development I just use only pH and time sensor). In the debug log starting with  `>>>` you can see query that consists of question mark (3F) and then two bytes that represents specific sensor reading, if you disable them, the query should be short and maybe it helps with timing.

(btw, if you need more help, it might be easier to call/zoom - according to the name of the screenshot - you speak Czech :) )

**Comment by tomp1k** [comment]
Díky moc za rychlou reakci!

Vypnul jsem všechny senzory a nechal jen pH. Nyní je log o poznání kratší a po vašem vysvětlení i srozumitelnější :-) 
[19:38:33][D][uart_debug:114]: >>> 3F:70:04     


"70:04" by tedy mělo odpovídat mému pH, které je aktuálně 7.3
Mám tušení, že komunikace mezi ESP a solničkou nefunguje, protože jsem nějaký pin špatně připájel. Asi to budu muset celé znovu projít. 

Děkuji moc za radu. Předpokládám tedy, že vám komponenta funguje dobře a chyba tedy není nikde v kódu :-)

**Comment by lipov3cz3k** [comment]
je to ještě trošku jinak. Pokud převedu řádek `>>> 3F:70:04` podle [ascii](https://www.ascii-code.com/) tabulky na znaky, tak z toho mám `?:p:EOT` (EOT je neviditelný znak End of Transmission) na tento příkaz (p - viz tabulka níže) by solnička měla zareagovat odpovědí a vlogu by mělo být něco jako `<<< 70:B3:02` což je `p : pH low byte : pH high byte` takže hodnota na displeji je 6.91

<img width="878" alt="Image" src="https://github.com/user-attachments/assets/65b64e44-dfd3-4022-96a6-af0242dc73f5" />

Při zapojení je důležité mít správně propojené RX a TX ... pokud se na to dívám ze strany ESP, tak mezi GND a pinem který mi bude reprezentovat TX (budou odcházet příkazy) bych měl naměřit nějaké volty (tuším že tam bylo 12V), tento drátek se připojí na pin RX na straně solničky (RX poznám tak, že mezi ním a GND bude 0V). A naopak TX ze strany solničky odesílá odpověď na RX ESP.

Moje aktuální konfigurace je
```yaml
....
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':');
      
external_components:
  - source:
      type: git
      url: https://github.com/lipov3cz3k/esphome-bspool-chlorinator
      ref: fix-units
    components: [ bs_pool ]
    refresh: 1min

bs_pool:
  update_interval: 15s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"

  - platform: bs_pool
    cell_current:
      name: Cell current
    cell_intensity:
      name: Cell intensity
    cell_voltage:
      name: Cell voltage
    ph:
      name: pH
    radox:
      name: ORP

binary_sensor:
  - platform: bs_pool
    alarm_redox_saturated:
      name: ORP probe saturated alarm
    alarm_overtemperature:
      name: Overtemperature inside the chlorinator
    alarm_open_circuit:
      name: Open circuit alarm
    alarm_water_flow:
      name: Lack of water flow alarm
    alarm_short_circuit:
      name: Short circuit alarm
    alarm_unit_stopped:
      name: P954 unit stopped alarm
    alarm_communication_error:
      name: Communication error to P954 alarm
    warning_low_salt:
      name: Too few salt
    warning_high_salt:
      name: Too much salt
    warning_ph_pump_overrun:
      name: pH problem, pump has run for too long
    warning_acid:
      name: Acid warning
    warning_clock_set:
      name: Clock has been set
    warning_probe_disconnected:
      name: ORP or chlorine probe disconnected
    status_output_voltage_polarity:
      name: Polarity of output voltage
    status_filter_pump_running:
      name: Filter pump running
    status_chlorination_process:
      name: Chlorination in process
    status_stopped_by_remote:
      name: Stopped by remote controller
    status_orp_sensor_stable:
      name: ORP sensor reading is stable
    status_salt_sensor_connected:
      name: Salt sensor connected
    status_electrode_cleaning:
      name: Electrode cleaning in process
    status_super_chlorination:
      name: Super-chlorination in process

switch:
  - platform: bs_pool
    user_is_outdoor:
      name: Pool is outdoor
    user_cover_switch_off:
      name: Cover switch off
    user_flow_switch_installed:
      name: Flow switch installed
    user_orp_displayed:
      name: ORP displayed
    user_ph_alarm:
      name: pH alarm
    user_ph_corrector_alkaline:
      name: pH corrector alkaline
    user_ph_control:
      name: pH control
    user_cover_installed:
      name: Cover installed
```

<img width="1190" alt="Image" src="https://github.com/user-attachments/assets/d8bb9ad3-dbbd-4fe7-a5ba-f270c1587854" />
