### ISSUE TITLE
Hodnota cell_voltage neodpovídá realitě

### ISSUE THREAD

**Issue by tomp1k** [lipov3cz3k/esphome-bspool-chlorinator#3]
Hodnota sensoru cell_voltage neopovídá realitě. Zdá se, že odpovídající hodnota je 10x větší. 

Možná upravit
this->cell_voltage_sensor_->publish_state(get_u16(message) / 100.0f);
      break;
 
na

this->cell_voltage_sensor_->publish_state(get_u16(message) / 10.0f);
      break;

**Comment by lipov3cz3k** [comment]
Mělo by to ukazovat v mV místo ve voltech - opravoval jsem to [zde](
https://github.com/lipov3cz3k/esphome-bspool-chlorinator/pull/2/files#diff-f8b95a3fea21579f4ecd280fd0e000e848aa502049b6d2c445522deeba3c195aR84). 
Máte aktuální verzi z main? (bez specifikované `ref: fix-units`, případně s nastavenou hodnotou `refresh`)
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/lipov3cz3k/esphome-bspool-chlorinator
    components: [ bs_pool ]
    refresh: 1min
```
